<Project>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ImplicitUsings>true</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <PackageTags>json;validation;guard</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Description>An efficient, allocation free JSON validation library for System.Text.Json, based on Source Generation.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>ICON.png</PackageIcon>
  </PropertyGroup>

  <PropertyGroup Condition="'$(CI)' != ''">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MinVer">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)/Resources/NuGet/README.md" Pack="true" PackagePath="" />
    <None Include="$(MSBuildThisFileDirectory)/Resources/NuGet/ICON.png" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>
